name: Build Ksign

on:
  workflow_dispatch:

env:
  CONFIGURATION: Release

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Use Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

      - name: Set build version from commit
        run: agvtool new-version -all "$(git rev-parse HEAD)"

      - name: Build Release
        run: |
          make CONFIGURATION="${CONFIGURATION}"
          mkdir -p "upload/${CONFIGURATION}"
          mv "packages/Ksign-${CONFIGURATION}.ipa" "upload/${CONFIGURATION}/"

      - name: Upload artifact (Release)
        uses: actions/upload-artifact@v4
        with:
          name: Ksign-${{ env.CONFIGURATION }}
          path: upload/${{ env.CONFIGURATION }}/*

  release:
    runs-on: macos-15
    needs: build
    steps:
      - name: Checkout (for version info)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: Ksign-*
          merge-multiple: true

      - name: Show files
        run: ls -lahR dist

      - name: Determine version
        shell: bash
        run: |
          VERSION="$(agvtool what-marketing-version -terse1 2>/dev/null | tail -n1 || true)"
          if [ -z "$VERSION" ]; then VERSION="$(date +%Y.%m.%d)-$(git rev-parse --short HEAD)"; fi
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Create/Update draft release
        uses: softprops/action-gh-release@v2
        with:
          name: Ksign v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            dist/**/*
          generate_release_notes: true
          draft: true
          fail_on_unmatched_files: false
          token: ${{ secrets.GITHUB_TOKEN }}
