name: Build Ksign Release IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Xcode 26.2
        run: |
          ls /Applications
          sudo xcode-select -s /Applications/Xcode_26.2.app/Contents/Developer
          xcodebuild -version

      - name: Build Ksign
        run: |
          make clean
          make

      - name: Prepare artifacts
        run: |
          mkdir -p upload
          mv packages/* upload/

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Ksign-IPA
          path: upload/*.ipa
          if-no-files-found: error
